"""Shared prospect model + provider interface. Every data vendor adapter
returns a list of Prospect objects so the rest of the engine is vendor-neutral."""
from dataclasses import dataclass, asdict, field
from typing import List, Optional
import hashlib


@dataclass
class Prospect:
    # Identity / dedupe
    source: str = "mock"            # "apollo" | "mock"
    source_id: str = ""            # provider's stable id for this person
    # Person
    first_name: str = ""
    last_name: str = ""
    title: str = ""
    email: str = ""
    phone: str = ""
    linkedin_url: str = ""
    # Company
    company: str = ""
    website: str = ""
    company_address: str = ""
    company_description: str = ""
    industry: str = ""
    employee_count: Optional[int] = None
    # Generated by our AI layer (filled in later in the pipeline)
    fit_reason: str = ""
    intro_email_subject: str = ""
    intro_email_body: str = ""
    tier: str = ""   # "core" | "bonus" | "spare" — which report section it's in

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}".strip()

    def dedupe_key(self) -> str:
        """The primary fingerprint (provider id if present). Kept for the
        ledger's primary key. For exclusion checks use identity_keys(), which
        also catches the same person arriving under a different provider id."""
        keys = self.identity_keys()
        return keys[0] if keys else "hash:unknown"

    def identity_keys(self) -> list:
        """ALL signals that identify this person. A prospect is a duplicate if
        ANY of these has been seen before -- this catches the same human
        appearing with a different provider id, a re-verified email, etc."""
        keys = []
        if self.source_id:
            keys.append(f"{self.source}:{self.source_id}")
        if self.email:
            keys.append("email:" + self.email.strip().lower())
        if self.linkedin_url:
            keys.append("li:" + self.linkedin_url.strip().lower().rstrip("/"))
        basis = f"{self.full_name}|{self.company}".strip().lower()
        if basis != "|":
            keys.append("hash:" + hashlib.sha1(basis.encode()).hexdigest()[:16])
        return keys

    def is_duplicate(self, seen: set) -> bool:
        return any(k in seen for k in self.identity_keys())

    def to_dict(self) -> dict:
        d = asdict(self)
        d["full_name"] = self.full_name
        d["dedupe_key"] = self.dedupe_key()
        return d


class ProspectProvider:
    """Interface: given a SearchSpec, yield up to `limit` prospects, skipping
    any whose dedupe_key is in `exclude_keys`."""

    def find(self, spec, limit: int, exclude_keys: set) -> List[Prospect]:
        raise NotImplementedError
